name: SimpleDatabase_Plugin
main: com.braydenwaugh.simpledatabaseplugin.SimpleDatabasePlugin
version: 1.0.0
author: Brayden Waugh [SanityPirate]
description: Implements a variety of commands that store useful player information in a database.
commands:
  sayhi:
    description: Make Minecraft say Hi!
    usage: /sayhi
  sethome:
    description: Save your current coordinates to the database.
    usage: /sethome [name]
  findhome:
    description: Load and List your homes and find their coordinates.
    usage: /findhome | [name] | [load]
  delhome:
    description: Delete a specified home.
    usage: /delhome [name]